
#include "ContactState.idl"
#include "std_msgs/msg/Header.idl"

module gazebo_msgs
{

module msg
{

struct ContactsState {
        
    std_msgs::msg::Header header;
    sequence<gazebo_msgs::msg::ContactState> states;

};

};  // module msg

};  // module gazebo_msgs
