 
#include "geometry_msgs/msg/Pose.idl" 
#include "geometry_msgs/msg/Twist.idl" 
 
module gazebo_msgs { module msg { 
 
struct LinkStates 
{ 
  sequence<string> name; 
  sequence<geometry_msgs::msg::Pose> pose; 
  sequence<geometry_msgs::msg::Twist> twist; 
}; 
 
}; };  // module msg::gazebo_msgs
