
module gazebo_msgs
{

module msg
{

struct ODEJointProperties {

    sequence<double> damping;
    sequence<double> hiStop;
    sequence<double> loStop;
    sequence<double> erp;
    sequence<double> cfm;
    sequence<double> stop_erp;
    sequence<double> stop_cfm;
    sequence<double> fudge_factor;
    sequence<double> fmax;
    sequence<double> vel;

};

};  // module msg

};  // module gazebo_msgs
