/* --- ContactsState type: ------------------------------------------------- */

/*
 * This is the ContactsState type.
 *
 * Broadcast all Contact states in world frame
 */
struct ContactsState {
        /*
         * Stamp
         */
        Header header;

        /*
         * Array of geom pairs in contact
         */
        sequence<ContactState> states;
};