
/* --- ModelStates type: --------------------------------------------------- */

/*
 * This is the ModelStates type.
 *
 * Broadcast all model states in world frame
 */
struct ModelStates {
        /*
         * Model names
         */
        sequence<string> name;

        /*
         * Desired pose in world frame
         */
        sequence<Pose> pose;

        /*
         * Desired twist in world frame
         */
        sequence<Twist> twist;
};