
module gazebo_msgs
{

module srv
{

struct SetLinkProperties_Request {

    string link_name;
    Pose com;
    boolean gravity_mode;
    double mass;
    double ixx;
    double ixy;
    double ixz;
    double iyy;
    double iyz;
    double izz;

};

};  // module srv

};  // module gazebo_msgs
