 
#include "geometry_msgs/msg/Pose.idl" 
 
module gazebo_msgs { module srv { 
 
struct SpawnModel_Request {  
    string model_name; 
    string model_xml; 
    string robot_namespace; 
    geometry_msgs::msg::Pose initial_pose; 
    string reference_frame; 
}; 
 
}; };  // module srv::gazebo_msgs 
